import React from'react';
import{ArrowRight,ChefHat,CircleDollarSign,ClipboardCheck,CreditCard,PackageCheck,RotateCcw,Store,Users,UtensilsCrossed}from'lucide-react';
import{activeOrder,menu,metrics,rupees}from'@munaffa/core';
import{useRestaurant}from'./store';

const go=r=>location.hash=r;
const roles=[['story','Story',Store],['app/guest','Guest',UtensilsCrossed],['app/waiter','Waiter',Users],['app/kitchen','Kitchen',ChefHat],['app/pos','POS',CreditCard],['app/stock','Stock',PackageCheck],['app/manager','Manager',ClipboardCheck],['app/owner','Owner',CircleDollarSign]];

function Shell({route,children}){const reset=useRestaurant(s=>s.reset);return <div className="shell"><aside><button className="brand" onClick={()=>go('story')}><span>M</span><b>Munaffa</b></button><small>CONNECTED PROTOTYPE</small>{roles.map(([r,label,I])=><button className={route===r?'active':''} onClick={()=>go(r)} key={r}><I/><span>{label}</span></button>)}<button className="reset" onClick={reset}><RotateCcw/> Reset restaurant</button></aside><main>{children}</main></div>}
function PageHead({eyebrow,title,body,action}){return <header className="pagehead"><div><small>{eyebrow}</small><h1>{title}</h1><p>{body}</p></div>{action}</header>}
function Empty({children}){return <div className="empty">{children}</div>}
function Timeline(){const events=useRestaurant(s=>s.state.events);return <section className="panel events"><header><div><h3>One event stream</h3><p>Every role below reads this same restaurant state.</p></div></header>{events.length?events.slice().reverse().map(e=><div className="event" key={e.id}><i/><div><b>{e.type}</b><small>{new Date(e.at).toLocaleTimeString()}</small></div><code>{JSON.stringify(e.payload)}</code></div>):<Empty>No restaurant events yet.</Empty>}</section>}

function Story(){return <div className="story"><section className="story-hero"><small>MUNAFFA · CLEAN REBUILD</small><h1>One order.<br/>One restaurant.<br/>One truth.</h1><p>This build starts from the operational spine instead of decoration. Table 12 is the canonical story: guest → waiter → kitchen → recipe → stock → payment → owner.</p><div><button onClick={()=>go('app/guest')}>Start at Table 12 <ArrowRight/></button><button className="secondary" onClick={()=>go('app/owner')}>Open Owner view</button></div></section><section className="story-track">{['Guest sits at Table 12','Order enters shared engine','Waiter accepts the same order','Kitchen starts the same items','Recipe usage writes stock movements','Items become ready and served','POS captures the same bill','Owner metrics recalculate from those events'].map((x,i)=><article key={x}><span>{String(i+1).padStart(2,'0')}</span><h2>{x}</h2></article>)}</section><section className="principle"><small>THE DIFFERENCE</small><h2>No role owns a fake copy of the restaurant.</h2><p>There is one restaurant state. The UI changes by role; the facts do not.</p></section></div>}

function Guest(){const state=useRestaurant(s=>s.state),dispatch=useRestaurant(s=>s.dispatch),o=activeOrder(state);const canCreate=!o||o.paymentStatus==='paid';return <><PageHead eyebrow="GUEST · TABLE 12" title="Order without breaking hospitality." body="QR is optional. This demo places the canonical Table 12 order into the same engine used by every staff surface." action={<button className="primary" disabled={!canCreate} onClick={()=>dispatch('ORDER_PLACED',{tableId:'T12',source:'guest',items:[{menuId:'paneer_tikka',qty:2},{menuId:'garlic_naan',qty:4}]})}>{canCreate?'Place Table 12 order':'Order already active'}</button>}/><div className="grid two"><section className="panel menu"><header><div><h3>Restaurant menu</h3><p>The Spice Room</p></div></header>{Object.values(menu).map(d=><div className="menurow" key={d.id}><div><b>{d.name}</b><small>{d.station}</small></div><strong>{rupees(d.price)}</strong></div>)}</section><OrderCard order={o}/></div><Timeline/></>}
function OrderCard({order}){if(!order)return <section className="panel"><header><div><h3>Table 12 order</h3><p>No active order.</p></div></header><Empty>Place the order to begin the end-to-end flow.</Empty></section>;return <section className="panel"><header><div><h3>{order.id} · Table {order.tableId.replace('T','')}</h3><p>{order.source} · {order.status}</p></div><span className={'status '+order.paymentStatus}>{order.paymentStatus}</span></header>{order.items.map(x=><div className="orderline" key={x.id}><span>{x.qty}× {x.name}</span><em className={'status '+x.status}>{x.status}</em><b>{rupees(x.qty*x.price)}</b></div>)}</section>}

function Waiter(){const state=useRestaurant(s=>s.state),dispatch=useRestaurant(s=>s.dispatch),o=activeOrder(state);return <><PageHead eyebrow="MUNAFFA SERVE" title="The waiter sees the same Table 12." body="Accept the guest order, then serve items only after the kitchen marks them ready." action={o&&o.status==='placed'?<button className="primary" onClick={()=>dispatch('ORDER_ACCEPTED',{orderId:o.id})}>Accept order</button>:null}/><div className="grid two"><OrderCard order={o}/><section className="panel"><header><div><h3>Service actions</h3><p>Actions are constrained by actual item state.</p></div></header>{o?o.items.map(i=><button className="actionrow" disabled={i.status!=='ready'} onClick={()=>dispatch('ITEM_SERVED',{orderId:o.id,itemId:i.id})} key={i.id}><span>{i.qty}× {i.name}</span><b>{i.status==='ready'?'Serve now':i.status}</b></button>):<Empty>No active table.</Empty>}</section></div><Timeline/></>}

function Kitchen(){const state=useRestaurant(s=>s.state),dispatch=useRestaurant(s=>s.dispatch),o=activeOrder(state);return <><PageHead eyebrow="KITCHEN · KDS" title="Production state, not a separate demo." body="Starting an item creates recipe-consumption stock movements. Ready state is immediately visible to waiter and manager."/><div className="kds">{['new','preparing','ready','served'].map(status=><section key={status}><h3>{status.toUpperCase()}</h3>{o?.items.filter(i=>i.status===status).map(i=><article key={i.id}><small>{o.id} · {i.station}</small><strong>{i.qty}× {i.name}</strong>{status==='new'&&<button onClick={()=>dispatch('ITEM_STARTED',{orderId:o.id,itemId:i.id})}>Start</button>}{status==='preparing'&&<button onClick={()=>dispatch('ITEM_READY',{orderId:o.id,itemId:i.id})}>Mark ready</button>}</article>)}{!o?.items.some(i=>i.status===status)&&<Empty>No items</Empty>}</section>)}</div><Timeline/></>}

function POS(){const state=useRestaurant(s=>s.state),dispatch=useRestaurant(s=>s.dispatch),o=activeOrder(state);const total=o?o.items.reduce((a,x)=>a+x.price*x.qty,0)-o.discount:0;return <><PageHead eyebrow="CASHIER · POS" title="The bill is the same order." body="No duplicate POS cart exists. This screen settles the exact order created at Table 12."/><div className="grid two"><OrderCard order={o}/><section className="panel bill"><header><div><h3>Bill</h3><p>Table 12</p></div></header><div className="billtotal"><span>Total</span><b>{rupees(total)}</b></div><button className="primary full" disabled={!o||o.paymentStatus==='paid'} onClick={()=>o&&dispatch('PAYMENT_CAPTURED',{orderId:o.id,method:'upi'})}>{o?.paymentStatus==='paid'?'Payment captured':'Pay with UPI'}</button></section></div><Timeline/></>}

function Stock(){const state=useRestaurant(s=>s.state),dispatch=useRestaurant(s=>s.dispatch);return <><PageHead eyebrow="STOCK · INVENTORY" title="The pantry moves when the kitchen moves." body="Recipe deductions, wastage and purchasing all write to the same immutable movement history." action={<button className="primary" onClick={()=>dispatch('PURCHASE_RECEIVED',{ingredientId:'paneer',qty:5000,unitCost:.34})}>Receive 5kg paneer</button>}/><section className="panel"><header><div><h3>Ingredient ledger</h3><p>Live quantities from restaurant state</p></div></header><div className="table"><div className="tr th"><span>Ingredient</span><span>Available</span><span>Avg cost</span><span>Action</span></div>{Object.entries(state.ingredients).map(([id,x])=><div className="tr" key={id}><b>{x.name}</b><span>{x.qty.toLocaleString()} {x.unit}</span><span>{rupees(x.costPerUnit*(x.unit==='g'||x.unit==='ml'?1000:1))}/{x.unit==='g'?'kg':x.unit==='ml'?'L':x.unit}</span><button disabled={x.qty<100} onClick={()=>dispatch('WASTE_LOGGED',{ingredientId:id,qty:100,reason:'prep'})}>Log 100{x.unit} waste</button></div>)}</div></section><Timeline/></>}

function Manager(){const state=useRestaurant(s=>s.state),o=activeOrder(state);return <><PageHead eyebrow="MANAGER · LIVE OUTLET" title="Manage exceptions from the same facts." body="Table state, kitchen readiness, inventory movements and payment state are projections of one event stream."/><div className="metrics"><Metric label="Table 12" value={state.tables.T12.status}/><Metric label="Order" value={o?.status||'none'}/><Metric label="Kitchen ready" value={o?`${o.items.filter(i=>i.status==='ready').length}/${o.items.length}`:'0/0'}/><Metric label="Payment" value={o?.paymentStatus||'none'}/></div><Timeline/></>}
function Metric({label,value,sub}){return <div className="metric"><small>{label}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</div>}

function Owner(){const state=useRestaurant(s=>s.state),m=metrics(state);return <><PageHead eyebrow="OWNER · COMMAND CENTER" title="Know what changed, why, and the rupee impact." body="Every number below is derived from the exact orders, stock movements, waste and payments created in this session."/><div className="metrics"><Metric label="Net sales" value={rupees(m.revenue)} sub={`${m.paidOrders} paid orders`}/><Metric label="Contribution" value={rupees(m.contribution)} sub="before fixed overhead"/><Metric label="Food cost" value={`${m.foodCostPct.toFixed(1)}%`} sub={rupees(m.ingredientCost)}/><Metric label="Potential leakage" value={rupees(m.potentialLeakage)} sub="waste + discounts"/></div><div className="grid two"><section className="panel money"><header><div><h3>Profit pulse</h3><p>Evidence-backed contribution bridge</p></div></header><div><span>{rupees(m.revenue)}<small>sales</small></span><i>−</i><span>{rupees(m.ingredientCost)}<small>ingredients</small></span><i>−</i><span>{rupees(m.paymentFees)}<small>payment fees</small></span><i>=</i><span className="good">{rupees(m.contribution)}<small>contribution</small></span></div></section><section className="panel"><header><div><h3>Leak evidence</h3><p>Only what has actually been logged</p></div></header>{state.waste.length?state.waste.slice().reverse().map(w=><div className="orderline" key={w.id}><span>{state.ingredients[w.ingredientId].name} · {w.reason}</span><b>{rupees(w.cost)}</b></div>):<Empty>No waste or discount leakage has been logged.</Empty>}</section></div><Timeline/></>}

export default function App({route}){const valid=roles.some(([r])=>r===route);const r=valid?route:'story';let page=r==='story'?<Story/>:r==='app/guest'?<Guest/>:r==='app/waiter'?<Waiter/>:r==='app/kitchen'?<Kitchen/>:r==='app/pos'?<POS/>:r==='app/stock'?<Stock/>:r==='app/manager'?<Manager/>:<Owner/>;return <Shell route={r}>{page}</Shell>}
