import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Canvas,useFrame,useThree}from'@react-three/fiber';
import{Environment,Float}from'@react-three/drei';
import*as THREE from'three';
import gsap from'gsap';
import{ScrollTrigger}from'gsap/ScrollTrigger';
import Lenis from'lenis';
import{createClient}from'@supabase/supabase-js';
import{ArrowRight,BarChart3,Boxes,ChefHat,CircleDollarSign,ClipboardCheck,CookingPot,CreditCard,LayoutDashboard,Menu as MenuIcon,PackageCheck,QrCode,ReceiptIndianRupee,Search,ShoppingBag,Sparkles,Store,Users,X}from'lucide-react';
import'./styles.css';

gsap.registerPlugin(ScrollTrigger);
const supabaseUrl=import.meta.env.VITE_SUPABASE_URL;
const supabaseKey=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
export const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

const PAGES={
 home:{eyebrow:'Restaurant Profit OS',title:'You know your sales. Now know your Munaffa.',body:'One connected operating system from the table to the kitchen to the bottom line.',accent:'#b9ef83'},
 product:{eyebrow:'The platform',title:'One restaurant. One living operating system.',body:'Orders, kitchen, stock, purchasing, guests and profit intelligence move as one.',accent:'#e7bf79'},
 profit:{eyebrow:'Profit OS',title:'Follow every rupee until it becomes profit.',body:'Turn recipes, waste, discounts, supplier prices and sales into decisions an owner can act on.',accent:'#b9ef83'},
 operations:{eyebrow:'Live operations',title:'See the restaurant move in real time.',body:'Table state, waiter response, KDS timing, bills and approvals in one operating cockpit.',accent:'#7fd7ff'},
 inventory:{eyebrow:'Inventory intelligence',title:'From bulk purchase to every plate.',body:'Recipe costing, theoretical usage, actual stock, wastage and supplier movements share one ledger.',accent:'#ffc771'},
 guest:{eyebrow:'Guest experience',title:'A digital menu that still feels like hospitality.',body:'QR ordering is optional, fast and restaurant-branded — with waiter, bill and feedback flows built in.',accent:'#ff997c'},
 ai:{eyebrow:'Munaffa Intelligence',title:'Turn restaurant noise into the next best action.',body:'Forecast demand, detect anomalies, surface profit leaks and explain what changed.',accent:'#a891ff'},
 pricing:{eyebrow:'Plans',title:'Start small. Prove the value. Grow from there.',body:'Plans designed around restaurant maturity, not feature overload.',accent:'#b9ef83'}
};
const NAV=[['Product','product'],['Profit OS','profit'],['Operations','operations'],['Inventory','inventory'],['Guest','guest'],['AI','ai'],['Pricing','pricing']];
const CHAPTERS={
 home:[['01','THE BILL','Sales enter as one number. Costs hide underneath.'],['02','THE TABLE','A guest scans, browses or orders with a waiter.'],['03','THE KITCHEN','The order becomes station work, timing and service.'],['04','THE STOCK','Every sold dish maps to theoretical ingredient use.'],['05','THE LEAK','Waste, variance and supplier changes separate from the healthy flow.'],['06','THE OWNER','Munaffa turns the entire restaurant into one decision layer.']],
 product:[['01','ONE SYSTEM','The restaurant appears as a living operational map.'],['02','ORDER ENGINE','QR, waiter, counter and delivery enter the same order stream.'],['03','KITCHEN','Tickets split by station and rejoin at expo.'],['04','INVENTORY','Recipes deduct theoretical stock and expose variance.'],['05','GUESTS','Visits, feedback and retention return to the same system.'],['06','PROFIT','Operational events resolve into contribution and action.']],
 profit:[['01','REVENUE','Gross sales become a transparent money stream.'],['02','VARIABLE COST','Ingredients, packaging, discounts and fees peel away.'],['03','VARIANCE','Ideal consumption separates from actual consumption.'],['04','LEAK DETECTOR','Potential leakage becomes visible in rupees.'],['05','SIMULATE','Test price, portion and supplier decisions before acting.'],['06','COMMAND','The owner sees what changed and why.']],
 operations:[['01','FLOOR','Tables pulse with their live service state.'],['02','ORDER','Customer and waiter orders merge into one session.'],['03','KDS','Tickets travel to the right preparation station.'],['04','EXPO','Completed items reunite into a table order.'],['05','SERVICE','Ready food, waiter calls and bills trigger response timers.'],['06','MANAGER','Exceptions rise to the top instead of hiding in reports.']],
 inventory:[['01','PURCHASE','Bulk stock enters through supplier receipts.'],['02','CONVERT','Kg, grams, litres, ml, packs and portions normalize.'],['03','RECIPE','Batch and dish recipes create ideal usage.'],['04','COUNT','Physical counts reveal the actual restaurant.'],['05','WASTE','Waste gets a reason, quantity and rupee impact.'],['06','FORECAST','Munaffa predicts runout and recommends purchasing.']],
 guest:[['01','SCAN','The table is identified instantly — no app required.'],['02','DISCOVER','A restaurant-branded menu prioritizes food, not software.'],['03','ORDER','Direct, waiter-confirmed or browse-only modes.'],['04','TRACK','Guests see a simple live order state.'],['05','SERVICE','Water, cutlery, waiter and bill requests become tasks.'],['06','RETURN','Feedback and loyalty close the visit loop.']],
 ai:[['01','OBSERVE','Munaffa watches operational patterns, not people.'],['02','COMPARE','Today is compared with recipe, history and targets.'],['03','DETECT','Anomalies become evidence-backed alerts.'],['04','FORECAST','Demand and stock move from reactive to predictive.'],['05','EXPLAIN','Every recommendation includes the numbers behind it.'],['06','ACT','Humans approve pricing, purchasing and operational changes.']],
 pricing:[['01','LAUNCH','QR, orders and basic operations for early restaurants.'],['02','GROWTH','Inventory, KDS, recipe costing and purchasing.'],['03','PROFIT','Full leakage intelligence, CRM and advanced analytics.'],['04','MULTI-OUTLET','Central visibility with outlet-level control.'],['05','PILOT','Start with measurable leakage before replacing existing systems.'],['06','ROI','The plan should earn its place by saving more than it costs.']]
};

function hashRoute(){return(location.hash||'#home').slice(1)}
function useRoute(){const[r,setR]=useState(hashRoute());useEffect(()=>{const f=()=>setR(hashRoute());addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);return r}
function go(route){document.body.classList.add('route-leaving');setTimeout(()=>{location.hash=route;scrollTo(0,0);document.body.classList.remove('route-leaving')},460)}
function useCinematicScroll(){const[p,setP]=useState(0);useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;let lenis;if(!reduced&&innerWidth>820){lenis=new Lenis({duration:1.05,smoothWheel:true});let id;const loop=t=>{lenis.raf(t);id=requestAnimationFrame(loop)};id=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(id);lenis.destroy()}}},[]);useEffect(()=>{let raf=0;const u=()=>{if(raf)return;raf=requestAnimationFrame(()=>{const h=document.documentElement.scrollHeight-innerHeight;setP(h?scrollY/h:0);raf=0})};addEventListener('scroll',u,{passive:true});u();return()=>removeEventListener('scroll',u)},[]);return p}
function useReveal(key){useEffect(()=>{const ctx=gsap.context(()=>{$$('.reveal').forEach(el=>gsap.fromTo(el,{y:70,opacity:0,filter:'blur(12px)'},{y:0,opacity:1,filter:'blur(0px)',ease:'none',scrollTrigger:{trigger:el,start:'top 88%',end:'top 55%',scrub:true}}));$$('.wordmark-ghost').forEach(el=>gsap.to(el,{xPercent:-18,ease:'none',scrollTrigger:{trigger:el.parentElement,start:'top bottom',end:'bottom top',scrub:true}}))});return()=>ctx.revert()},[key])}
const $$=s=>[...document.querySelectorAll(s)];

function Table({x,z,active=false}){return <group position={[x,0,z]}><mesh position={[0,.38,0]}><boxGeometry args={[1.25,.08,.8]}/><meshStandardMaterial color={active?'#31563f':'#493b2c'} roughness={.5}/></mesh>{[[-.48,.18,-.5],[.48,.18,-.5],[-.48,.18,.5],[.48,.18,.5]].map((p,i)=><mesh key={i} position={p}><boxGeometry args={[.32,.36,.32]}/><meshStandardMaterial color="#1b1d18"/></mesh>)}</group>}
function Restaurant({mode,progress}){const root=useRef(),ticket=useRef(),phone=useRef(),pantry=useRef(),dashboard=useRef(),core=useRef();const{camera,pointer}=useThree();const accent=new THREE.Color(PAGES[mode]?.accent||'#b9ef83');useFrame((_,dt)=>{const p=progress;const stage=p*5;const tx=mode==='inventory'?-1.5:mode==='guest'?1.5:mode==='profit'?-.5:0;root.current.rotation.y=THREE.MathUtils.lerp(root.current.rotation.y,(pointer.x*.09)+(p-.5)*.35,Math.min(1,dt*3));root.current.position.x=THREE.MathUtils.lerp(root.current.position.x,tx*(.2+.8*p),dt*2.5);ticket.current.position.lerp(new THREE.Vector3(-2.4+Math.min(stage,2)*2.2,1.7-Math.max(0,stage-1)*.22,1.2-Math.min(stage,3)*.95),dt*3);ticket.current.rotation.z+=dt*.25;phone.current.position.y=THREE.MathUtils.lerp(phone.current.position.y,p<.34?1.7:-1.5,dt*3);pantry.current.scale.setScalar(THREE.MathUtils.lerp(pantry.current.scale.x,p>.42?1.08:.8,dt*3));dashboard.current.position.z=THREE.MathUtils.lerp(dashboard.current.position.z,p>.76?-.5:-7,dt*3);dashboard.current.rotation.y=THREE.MathUtils.lerp(dashboard.current.rotation.y,(pointer.x*.12),dt*3);core.current.rotation.y+=dt*(.5+p);core.current.rotation.x+=dt*.2;const target=p<.16?new THREE.Vector3(0,4.7,9.8):p<.34?new THREE.Vector3(3.8,2.1,6.2):p<.55?new THREE.Vector3(-3.8,2.5,5.8):p<.76?new THREE.Vector3(3,2.7,6.5):new THREE.Vector3(0,2.2,8.5);camera.position.lerp(target,Math.min(1,dt*1.9));camera.lookAt(0,.8,0)});return <group ref={root}>
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,0,0]}><planeGeometry args={[13,10,22,18]}/><meshStandardMaterial color="#101712" roughness={.86}/></mesh>
 <group position={[-2.5,0,-.2]}>{[-1.6,0,1.6].map((x,i)=><Table key={x} x={x} z={i%2?1.4:-1.1} active={i===1}/>)}</group>
 <group position={[2.7,.6,-1.1]}><mesh><boxGeometry args={[4,1.2,1.1]}/><meshStandardMaterial color="#b8a17f" metalness={.25}/></mesh><mesh position={[0,.9,-.25]}><boxGeometry args={[3.4,.55,.08]}/><meshStandardMaterial color="#202821" emissive="#163323" emissiveIntensity={.35}/></mesh></group>
 <group ref={pantry} position={[3.5,.1,2.25]}>{[0,.9,1.8].map((y,j)=><group key={y} position={[0,y,0]}>{[-1,-.35,.35,1].map((x,i)=><mesh key={x} position={[x,.35,0]}><boxGeometry args={[.5,.58,.62]}/><meshStandardMaterial color={['#e9bd72','#8abf6d','#d87553','#d9d3a8'][i]}/></mesh>)}</group>)}</group>
 <Float speed={1.5} rotationIntensity={.15} floatIntensity={.25}><group ref={phone} position={[2,1.7,1.4]} rotation={[0,-.45,.08]}><mesh><boxGeometry args={[1.05,2.1,.12]}/><meshStandardMaterial color="#050706" metalness={.8}/></mesh><mesh position={[0,0,.07]}><planeGeometry args={[.9,1.9]}/><meshBasicMaterial color="#f5f1e8"/></mesh>{[-.55,-.15,.25,.65].map((y,i)=><mesh key={y} position={[0,y,.078]}><planeGeometry args={[.68,.22]}/><meshBasicMaterial color={i===0?'#1f6b46':'#d9cab0'}/></mesh>)}</group></Float>
 <group ref={ticket} position={[-2.4,1.7,1.2]}><mesh><boxGeometry args={[.75,1.15,.04]}/><meshStandardMaterial color="#f6eedc" emissive="#5b4b2d" emissiveIntensity={.08}/></mesh>{[-.3,-.05,.2,.43].map((y,i)=><mesh key={y} position={[0,y,.03]}><planeGeometry args={[.48,.035]}/><meshBasicMaterial color={i===3?accent:'#6b675f'}/></mesh>)}</group>
 <group position={[0,1.25,-2.6]}>{Array.from({length:22}).map((_,i)=>{const a=i/22*Math.PI*2;return <mesh key={i} position={[Math.cos(a)*(2.2+(i%3)*.25),Math.sin(a*2)*.55,Math.sin(a)*(2.2+(i%3)*.25)]}><sphereGeometry args={[.045+(i%4)*.012,10,10]}/><meshBasicMaterial color={i%5===0?'#ff735c':PAGES[mode]?.accent||'#b9ef83'}/></mesh>})}</group>
 <group ref={core} position={[0,1.6,-1.9]}><mesh rotation={[Math.PI/2,0,0]}><torusGeometry args={[1.15,.055,12,80]}/><meshBasicMaterial color={accent}/></mesh><mesh><icosahedronGeometry args={[.45,2]}/><meshStandardMaterial color="#102a1c" emissive={accent} emissiveIntensity={.8} wireframe/></mesh></group>
 <group ref={dashboard} position={[0,1.7,-7]}>{[-1.65,-.55,.55,1.65].map((x,i)=><mesh key={x} position={[x,.55+(i%2)*.15,0]}><boxGeometry args={[.9,.75,.05]}/><meshStandardMaterial color={i===3?'#5a1717':'#e9efe9'} emissive={i===3?'#ff503f':'#17291d'} emissiveIntensity={.22}/></mesh>)}<mesh position={[0,-.45,0]}><boxGeometry args={[4.4,.75,.05]}/><meshStandardMaterial color="#eff4ee" emissive="#193522" emissiveIntensity={.12}/></mesh></group>
 </group>}
function FlowParticles({mode}){const ref=useRef();const points=useMemo(()=>{const a=new Float32Array(540);for(let i=0;i<180;i++){a[i*3]=(Math.random()-.5)*14;a[i*3+1]=Math.random()*7;a[i*3+2]=(Math.random()-.5)*12}return a},[]);useFrame((_,dt)=>{ref.current.rotation.y+=dt*.025;ref.current.position.y=Math.sin(performance.now()/1400)*.08});return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" args={[points,3]}/></bufferGeometry><pointsMaterial size={.026} transparent opacity={.38} color={PAGES[mode]?.accent||'#b9ef83'} depthWrite={false}/></points>}
function World({mode,progress}){return <Canvas dpr={[1,1.25]} camera={{fov:42,position:[0,4.7,9.8]}} gl={{antialias:true,powerPreference:'high-performance'}}><color attach="background" args={['#050907']}/><fog attach="fog" args={['#050907',7,22]}/><ambientLight intensity={.6}/><directionalLight position={[5,7,4]} intensity={2.2} color="#fff0d3"/><pointLight position={[-4,3,2]} intensity={25} distance={10} color={PAGES[mode]?.accent||'#b9ef83'}/><Restaurant mode={mode} progress={progress}/><FlowParticles mode={mode}/><Environment preset="warehouse"/></Canvas>}

function Header({onMenu}){return <header className="site-header"><button className="brand" onClick={()=>go('home')}><span className="brand-mark">M</span><span>Munaffa</span></button><nav>{NAV.slice(0,5).map(([l,r])=><button key={r} onClick={()=>go(r)}>{l}</button>)}</nav><div className="header-actions"><button className="quiet" onClick={()=>go('login')}>Sign in</button><button className="pill" onClick={()=>go('app/owner')}>Live demo</button><button className="menu-btn" onClick={onMenu}><MenuIcon size={19}/></button></div></header>}
function MenuOverlay({open,onClose}){return <div className={'menu-overlay '+(open?'open':'')}><button className="close" onClick={onClose}><X/></button><div className="menu-copy"><span>Explore Munaffa</span><h2>The restaurant becomes the navigation.</h2><p>Move from profit to operations to inventory as one connected system.</p></div><div className="menu-grid">{NAV.map(([l,r],i)=><button onClick={()=>{onClose();go(r)}} key={r}><small>0{i+1}</small><strong>{l}</strong><span>{['Know the product','Find the leaks','Run the floor','Control stock','Design the visit','Predict & explain','Choose your plan'][i]}</span><ArrowRight/></button>)}</div></div>}
function Marketing({page}){const p=useCinematicScroll();const[menu,setMenu]=useState(false);useReveal(page);const data=PAGES[page]||PAGES.home;const chapters=CHAPTERS[page]||CHAPTERS.home;return <div className="marketing" style={{'--accent':data.accent}}><div className="canvas-wrap"><World mode={page} progress={p}/></div><Header onMenu={()=>setMenu(true)}/><MenuOverlay open={menu} onClose={()=>setMenu(false)}/><main>
 <section className="hero"><div className="hero-copy reveal"><div className="eyebrow">{data.eyebrow}</div><h1>{data.title}</h1><p>{data.body}</p><div className="hero-actions"><button className="pill big" onClick={()=>go('app/owner')}>Enter live product <ArrowRight/></button><button className="ghost" onClick={()=>scrollTo({top:innerHeight*1.1,behavior:'smooth'})}>Scroll the story</button></div></div><div className="hero-meter"><span>SCROLL</span><i style={{height:`${Math.max(6,p*100)}%`}}/></div><div className="wordmark-ghost">MUNAFFA</div></section>
 {chapters.map((c,i)=><section className={'chapter '+(i%2?'right':'left')} key={c[0]}><div className="chapter-copy reveal"><small>{c[0]} / 06</small><h2>{c[1]}</h2><p>{c[2]}</p>{i===2&&<div className="micro-flow"><span>ORDER</span><i/><span>KITCHEN</span><i/><span>STOCK</span><i/><span>₹</span></div>}{i===4&&<div className="signal"><b>Potential leakage</b><strong>₹4,820</strong><span>Ingredient variance · waste · discounts · supplier delta</span></div>}</div></section>)}
 <section className="conversion"><div className="reveal"><span className="eyebrow">Built for real restaurants</span><h2>Good food.<br/>Better margins.<br/>A clearer tomorrow.</h2><p>See the operating product with every role connected to the same restaurant.</p><button className="pill big" onClick={()=>go('app/owner')}>Open the full prototype <ArrowRight/></button></div></section>
 </main><footer><b>Munaffa</b><span>Know where every rupee goes.</span><div>{NAV.map(([l,r])=><button key={r} onClick={()=>go(r)}>{l}</button>)}</div></footer></div>}

const DEMO={sales:92480,contribution:56320,foodCost:31.8,leak:4820,orders:183,occupied:27};
const initialTables=Array.from({length:20},(_,i)=>({id:`T${String(i+1).padStart(2,'0')}`,state:['free','dining','prep','ready','bill'][i%5],mins:(i*7)%36+2,waiter:['Aman','Riya','Rahul'][i%3]}));
const stock=[['Paneer','13.2 kg','₹326/kg','2.9 days','low'],['Chicken','28.7 kg','₹242/kg','4.1 days','ok'],['Cream','4.2 L','₹210/L','2.1 days','low'],['Tomato','31.4 kg','₹44/kg','5.4 days','ok'],['Butter','8.6 kg','₹518/kg','6.8 days','ok']];
const menuItems=[['Paneer Tikka',349,'Veg','4.8'],['Butter Chicken',449,'Non-veg','4.7'],['Dal Makhani',329,'Veg','4.9'],['Garlic Naan',89,'Veg','4.6'],['Cold Coffee',189,'Veg','4.8']];
function Metric({label,value,delta,bad}){return <div className="metric"><span>{label}</span><strong className={bad?'bad':''}>{value}</strong><small>{delta}</small></div>}
function Sidebar({role,setRole}){const links=[['owner',LayoutDashboard],['manager',Store],['waiter',Users],['kitchen',ChefHat],['stock',Boxes],['admin',Sparkles],['guest',QrCode]];return <aside className="sidebar"><button className="brand app-brand" onClick={()=>go('home')}><span className="brand-mark">M</span><span>Munaffa</span></button><div className="role-label">DEMO ROLE</div>{links.map(([r,I])=><button className={r===role?'active':''} key={r} onClick={()=>{setRole(r);location.hash='app/'+r}}><I size={18}/><span>{r[0].toUpperCase()+r.slice(1)}</span></button>)}<div className="sidebar-bottom"><span className="health-dot"/>The Spice Room<br/><small>Connaught Place · Online</small></div></aside>}
function Owner(){return <><div className="page-title"><div><span className="eyebrow dark">OWNER COMMAND CENTER</span><h1>Good evening, Krishna.</h1><p>Your restaurant is performing normally. Three things need attention.</p></div><button className="date-chip">Today⌄</button></div><div className="metrics"><Metric label="Net sales" value="₹92,480" delta="↑ 12% vs last Sunday"/><Metric label="Contribution" value="₹56,320" delta="↑ 8%"/><Metric label="Food cost" value="31.8%" delta="↓ 2.4 pts"/><Metric label="Potential leakage" value="₹4,820" delta="↑ 18%" bad/></div><div className="dash-grid"><div className="panel span2"><PanelHead t="Profit pulse" s="Where today's money is going"/><div className="money-flow"><div><b>₹92,480</b><span>sales</span></div><i/><div className="deductions"><span>−₹29,410 ingredients</span><span>−₹2,120 discounts</span><span>−₹1,480 waste</span><span>−₹3,150 fees + variable</span></div><i/><div className="healthy"><b>₹56,320</b><span>contribution</span></div></div><div className="spark-bars">{[34,44,39,57,51,66,61,78,72,88,82,96].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div></div><div className="panel"><PanelHead t="Needs attention" s="Prioritized by rupee impact"/><Alert t="Ingredient variance" v="₹1,820"/><Alert t="Paneer stock low" v="2.9 days"/><Alert t="Table 14 delayed" v="17 min"/><Alert t="Refund approval" v="₹780"/></div><div className="panel span2"><PanelHead t="Live restaurant" s="27 of 38 tables occupied"/><Floor mini/></div><div className="panel"><PanelHead t="Top profit leaks" s="Today's controllable variance"/>{[['Paneer variance','₹816'],['Recorded waste','₹950'],['Discount leakage','₹740'],['Supplier delta','₹620']].map(x=><div className="row" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div></>}
function PanelHead({t,s}){return <div className="panel-head"><div><h3>{t}</h3><span>{s}</span></div><button>•••</button></div>}
function Alert({t,v}){return <button className="alert"><span className="alert-dot"/><div><b>{t}</b><small>Review now</small></div><strong>{v}</strong></button>}
function Floor({mini=false}){return <div className={'floor '+(mini?'mini':'')}>{initialTables.map(t=><button key={t.id} className={'table '+t.state}><b>{t.id}</b><span>{t.state}</span><small>{t.mins}m · {t.waiter}</small></button>)}</div>}
function Manager(){return <><div className="page-title"><div><span className="eyebrow dark">OUTLET CONTROL CENTER</span><h1>Today at Connaught Place.</h1><p>Restaurant status: <b>BUSY</b></p></div><button className="pill">Open shift</button></div><div className="metrics"><Metric label="Tables occupied" value="27 / 38" delta="72% occupancy"/><Metric label="Orders" value="143" delta="12 preparing"/><Metric label="Sales" value="₹67,830" delta="Dinner building"/><Metric label="Staff requests" value="4" delta="2 need action" bad/></div><div className="dash-grid"><div className="panel span2"><PanelHead t="Floor control" s="Tap a table for service timeline"/><Floor/></div><div className="panel"><PanelHead t="Action queue" s="Exceptions only"/><Alert t="Food ready — T17" v="5m"/><Alert t="Refund request" v="₹780"/><Alert t="Waiter call — T05" v="1m"/><Alert t="Chicken low" v="4.1d"/></div><div className="panel span3"><PanelHead t="Shift timeline" s="Service events across the restaurant"/><div className="timeline">{['7:42 T14 seated','7:45 order started','7:48 submitted','7:49 kitchen accepted','8:01 two items ready','8:04 first course served','8:17 second course ready'].map((x,i)=><div key={x}><i className={i===6?'warn':''}/><span>{x}</span></div>)}</div></div></div></>}
function Waiter(){const[items,setItems]=useState(0);return <><div className="page-title"><div><span className="eyebrow dark">MUNAFFA SERVE</span><h1>My tables.</h1><p>Fast enough to use with one hand during a rush.</p></div><button className="pill" onClick={()=>setItems(x=>x+1)}>+ Add demo item</button></div><div className="phone-workspace"><div className="phone-shell"><div className="phone-top">9:41 <b>Munaffa Serve</b><span>•••</span></div><h2>My tables</h2>{initialTables.slice(0,6).map(t=><button className="waiter-table" key={t.id}><span><b>{t.id}</b><small>{t.mins} min · {t.waiter}</small></span><em className={t.state}>{t.state}</em></button>)}<div className="phone-nav"><b>Tables</b><span>Orders</span><span>Requests</span><span>Me</span></div></div><div className="panel order-detail"><PanelHead t="Table 12" s="6 guests · 24 minutes"/><div className="ticket-row"><b>2× Paneer Tikka</b><span className="ready">READY</span></div><div className="ticket-row"><b>1× Butter Chicken</b><span>PREPARING</span></div><div className="ticket-row"><b>4× Butter Naan</b><span>PREPARING</span></div>{items>0&&<div className="ticket-row"><b>{items}× Cold Coffee</b><span>NEW</span></div>}<button className="pill wide">+ Add items</button></div></div></>}
function Kitchen(){const[lanes,setLanes]=useState({T12:'new',T08:'prep',T03:'ready',T17:'new'});const move=id=>setLanes(s=>({...s,[id]:s[id]==='new'?'prep':s[id]==='prep'?'ready':'ready'}));return <><div className="page-title"><div><span className="eyebrow dark">MUNAFFA KITCHEN</span><h1>Dinner service.</h1><p>ALL · TANDOOR · CURRY · CHINESE · BAR · DESSERT</p></div><button className="date-chip">Expo mode</button></div><div className="kds">{['new','prep','ready'].map(l=><div className="kds-lane" key={l}><h3>{l.toUpperCase()} <span>{Object.values(lanes).filter(x=>x===l).length}</span></h3>{Object.entries(lanes).filter(([,v])=>v===l).map(([id])=><button className={'kds-card '+l} onClick={()=>move(id)} key={id}><div><b>{id}</b><small>04:{id.slice(-1)}8</small></div><strong>{id==='T12'?'2 Paneer Tikka':'1 Butter Chicken'}</strong><span>• Medium spice<br/>• No onion</span><em>{l==='new'?'START':l==='prep'?'MARK READY':'READY FOR SERVICE'}</em></button>)}</div>)}</div></>}
function Stock(){const[waste,setWaste]=useState(0);return <><div className="page-title"><div><span className="eyebrow dark">MUNAFFA STOCK</span><h1>Inventory health.</h1><p>₹1.84L stock value · 3 low · 2 expiring · 1 variance</p></div><button className="pill" onClick={()=>setWaste(x=>x+1)}>Log waste</button></div><div className="metrics"><Metric label="Stock value" value="₹1.84L" delta="Across outlet"/><Metric label="Low items" value="3" delta="2 urgent" bad/><Metric label="Count variance" value="−₹1,280" delta="Needs approval" bad/><Metric label="Waste today" value={'₹'+(1120+waste*180)} delta="Recorded"/></div><div className="panel"><PanelHead t="Current stock" s="Forecast uses trailing demand"/><div className="stock-table"><div className="stock-row head"><span>Ingredient</span><span>Available</span><span>Avg cost</span><span>Runout</span><span>Status</span></div>{stock.map(x=><div className="stock-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><span>{x[2]}</span><span>{x[3]}</span><em className={x[4]}>{x[4]}</em></div>)}</div></div></>}
function Admin(){return <><div className="page-title"><div><span className="eyebrow dark">MUNAFFA HQ</span><h1>Network overview.</h1><p>Internal platform administration — never exposed to restaurants.</p></div><button className="date-chip">Production⌄</button></div><div className="metrics"><Metric label="Active outlets" value="411" delta="96.2% today"/><Metric label="GMV today" value="₹2.84 Cr" delta="41,082 orders"/><Metric label="MRR" value="₹18.4L" delta="↑ 6.1%"/><Metric label="Incidents" value="7" delta="3 need action" bad/></div><div className="dash-grid"><div className="panel span2"><PanelHead t="Restaurant network" s="Sync, payments and KDS health"/>{['The Spice Room','Roast & Co.','Kefi','Urban Kafe','Bawarchi'].map((x,i)=><div className="row" key={x}><span><span className={'health-dot '+(i===3?'warn':'')}/>{x}</span><b>{i===3?'Payment 8.4% fail':'Healthy'}</b></div>)}</div><div className="panel"><PanelHead t="SaaS health" s="Subscription signals"/><Alert t="Trials ending" v="14"/><Alert t="Churn risk" v="11"/><Alert t="Failed payment" v="8"/></div><div className="panel span3"><PanelHead t="Onboarding pipeline" s="From trial to live outlet"/><div className="pipeline">{['Lead 64','Trial 29','Menu mapped 18','Staff trained 12','Go-live 9'].map(x=><div key={x}>{x}</div>)}</div></div></div></>}
function Guest(){const[cart,setCart]=useState([]);const add=x=>setCart(c=>[...c,x]);return <><div className="page-title"><div><span className="eyebrow dark">MUNAFFA GUEST</span><h1>Table 12 experience.</h1><p>No mandatory app. No mandatory login. Restaurant branding first.</p></div><button className="pill">Preview QR</button></div><div className="guest-layout"><div className="guest-phone"><div className="restaurant-cover"><small>THE SPICE ROOM</small><h2>Good evening 👋</h2><span>Table 12 · ★ 4.7 · Open until 11:30 PM</span></div><div className="menu-tabs"><b>Popular</b><span>Starters</span><span>Mains</span><span>Drinks</span></div>{menuItems.map(m=><div className="dish" key={m[0]}><div className="dish-photo">{m[0][0]}</div><div><b>{m[0]}</b><small>★ {m[3]} · {m[2]}</small><strong>₹{m[1]}</strong></div><button onClick={()=>add(m)}>+</button></div>)}</div><div className="panel cart-panel"><PanelHead t="Table 12 cart" s={`${cart.length} items`}/>{cart.length===0?<div className="empty">Add a dish from the menu.</div>:cart.map((m,i)=><div className="row" key={i}><span>{m[0]}</span><b>₹{m[1]}</b></div>)}<button className="pill wide" disabled={!cart.length}>Send order {cart.length?`· ₹${cart.reduce((a,b)=>a+b[1],0)}`:''}</button><div className="service-buttons"><button>Water</button><button>Cutlery</button><button>Call waiter</button><button>Bill</button></div></div></div></>}
function Login(){const[email,setEmail]=useState('owner@demo.munaffa.in'),[status,setStatus]=useState('');const sign=async()=>{if(!supabase){setStatus('Demo mode — opening Owner Command Center.');setTimeout(()=>go('app/owner'),500);return}const{error}=await supabase.auth.signInWithOtp({email});setStatus(error?error.message:'Magic link sent. Check your email.')};return <div className="login"><button className="brand" onClick={()=>go('home')}><span className="brand-mark">M</span><span>Munaffa</span></button><div className="login-card"><span className="eyebrow dark">SECURE ACCESS</span><h1>Run the restaurant.<br/>Know the profit.</h1><p>Use Supabase magic-link authentication when configured, or enter demo mode locally.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="pill wide" onClick={sign}>Continue</button><small>{status}</small></div></div>}
function OperatingApp({initialRole}){const[role,setRole]=useState(initialRole||'owner');useEffect(()=>{const r=hashRoute().split('/')[1];if(r)setRole(r)},[initialRole]);return <div className="ops"><Sidebar role={role} setRole={setRole}/><main className="ops-main"><div className="ops-top"><div className="ops-search"><Search size={16}/><span>Search restaurant, order, ingredient…</span></div><div><button>?</button><button>🔔</button><span className="avatar">KT</span></div></div>{role==='owner'?<Owner/>:role==='manager'?<Manager/>:role==='waiter'?<Waiter/>:role==='kitchen'?<Kitchen/>:role==='stock'?<Stock/>:role==='admin'?<Admin/>:<Guest/>}</main></div>}
function App(){const route=useRoute();if(route==='login')return <Login/>;if(route.startsWith('app/'))return <OperatingApp initialRole={route.split('/')[1]}/>;return <><div className="route-curtain"/><Marketing page={PAGES[route]?route:'home'}/></>}
createRoot(document.getElementById('root')).render(<App/>);
