import React,{useMemo,useState}from'react';
import{ArrowLeft,ArrowRight,Clock,MapPin,Navigation,Search,Star,UtensilsCrossed}from'lucide-react';

const go=r=>location.hash=r;
const venues=[
 {id:'spice-room',name:'The Spice Room',type:'restaurant',area:'Connaught Place',lat:28.6315,lng:77.2167,cuisine:'North Indian · Modern Indian',rating:4.7,price:'₹₹₹',eta:'15–20 min',tags:['Dine-in','Direct order','Table service']},
 {id:'roast-house',name:'Roast House',type:'cafe',area:'Sector 18, Noida',lat:28.5706,lng:77.3219,cuisine:'Coffee · Bakery · Brunch',rating:4.6,price:'₹₹',eta:'10–15 min',tags:['Cafe','Pickup','Direct order']},
 {id:'courtyard-dining',name:'Courtyard Dining',type:'hotel-fb',area:'Aerocity',lat:28.5522,lng:77.1207,cuisine:'Hotel dining · Global',rating:4.8,price:'₹₹₹₹',eta:'20–25 min',tags:['Reservation','Hotel F&B','Table service']},
 {id:'dash-bowl',name:'Dash Bowl',type:'qsr',area:'Sector 62, Noida',lat:28.6270,lng:77.3725,cuisine:'Bowls · Wraps · Fast casual',rating:4.5,price:'₹₹',eta:'8–12 min',tags:['QSR','Pickup','Direct order']},
 {id:'green-table',name:'Green Table',type:'restaurant',area:'Greater Kailash',lat:28.5482,lng:77.2368,cuisine:'Vegetarian · Seasonal',rating:4.7,price:'₹₹₹',eta:'15–20 min',tags:['Vegetarian','Dine-in','Reservation']},
 {id:'bean-yard',name:'Bean Yard',type:'cafe',area:'Indirapuram',lat:28.6408,lng:77.3716,cuisine:'Coffee · Desserts',rating:4.4,price:'₹₹',eta:'10–15 min',tags:['Cafe','Work friendly','Pickup']}
];
const radians=x=>x*Math.PI/180;
function km(a,b){if(!a)return null;const R=6371,dLat=radians(b.lat-a.lat),dLon=radians(b.lng-a.lng),s=Math.sin(dLat/2)**2+Math.cos(radians(a.lat))*Math.cos(radians(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
const labels={all:'All',restaurant:'Restaurants',cafe:'Cafés','hotel-fb':'Hotel dining',qsr:'QSR'};

function VenueCard({v,distance}){return <button className="venue-card" onClick={()=>go(`venue/${v.id}`)}><div className={'venue-art '+v.type}><span>{v.type==='cafe'?'CAFÉ':v.type==='hotel-fb'?'HOTEL F&B':v.type==='qsr'?'QSR':'RESTAURANT'}</span></div><div className="venue-body"><div className="venue-title"><div><h3>{v.name}</h3><p>{v.cuisine}</p></div><b><Star/> {v.rating}</b></div><div className="venue-meta"><span><MapPin/>{v.area}</span>{distance!=null&&<span><Navigation/>{distance.toFixed(1)} km</span>}<span>{v.price}</span></div><div className="venue-tags">{v.tags.map(t=><span key={t}>{t}</span>)}</div></div></button>}

export function Discovery(){const[q,setQ]=useState(''),[type,setType]=useState('all'),[loc,setLoc]=useState(null),[locationState,setLocationState]=useState('idle');
 const useLocation=()=>{if(!navigator.geolocation){setLocationState('unsupported');return}setLocationState('loading');navigator.geolocation.getCurrentPosition(p=>{setLoc({lat:p.coords.latitude,lng:p.coords.longitude});setLocationState('ready')},()=>setLocationState('denied'),{enableHighAccuracy:false,timeout:8000,maximumAge:300000})};
 const list=useMemo(()=>venues.map(v=>({...v,distance:km(loc,v)})).filter(v=>(type==='all'||v.type===type)&&(`${v.name} ${v.cuisine} ${v.area}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>loc?(a.distance??999)-(b.distance??999):b.rating-a.rating),[q,type,loc]);
 return <main className="discover-shell"><header className="discover-nav"><button className="cine-brand" onClick={()=>go('story')}><i>M</i><b>Munaffa</b></button><div><button onClick={()=>go('app/guest')}>Table QR demo</button><button onClick={()=>go('auth')}>Account</button></div></header><section className="discover-hero"><small>MUNAFFA GUEST</small><h1>Find a place.<br/>Keep the relationship direct.</h1><p>Prototype discovery for restaurants, cafés, QSRs and hotel dining. Demo venues are fictional; production listings require verified venue data.</p><div className="discover-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Restaurant, café, cuisine or area"/><button onClick={useLocation}><Navigation/>{locationState==='loading'?'Locating…':locationState==='ready'?'Using my location':'Near me'}</button></div>{locationState==='denied'&&<p className="location-note">Location access was not granted. Discovery still works by search and category.</p>}</section><section className="discover-content"><div className="discover-filters">{Object.entries(labels).map(([id,label])=><button className={type===id?'active':''} onClick={()=>setType(id)} key={id}>{label}</button>)}</div><div className="venue-grid">{list.map(v=><VenueCard key={v.id} v={v} distance={v.distance}/>)}</div></section></main>}

export function Venue({id}){const v=venues.find(x=>x.id===id)||venues[0];const[booked,setBooked]=useState(false);return <main className="venue-page"><header><button onClick={()=>go('discover')}><ArrowLeft/> Discovery</button><button className="cine-brand" onClick={()=>go('story')}><i>M</i><b>Munaffa</b></button><button onClick={()=>go('auth')}>Account</button></header><section className={'venue-hero '+v.type}><div><small>{v.type.toUpperCase()}</small><h1>{v.name}</h1><p>{v.cuisine} · {v.area}</p><div><span><Star/> {v.rating}</span><span>{v.price}</span><span><Clock/> {v.eta}</span></div></div></section><section className="venue-detail"><article><small>DIRECT HOSPITALITY</small><h2>The venue owns the guest relationship.</h2><p>Munaffa discovery is designed to hand the guest into the restaurant’s own service flow instead of creating a separate operational island.</p><div className="venue-actions"><button className="primary" onClick={()=>go('app/guest')}><UtensilsCrossed/> Open digital menu</button><button className="secondary" onClick={()=>setBooked(true)}>{booked?'✓ Table reserved':'Reserve a table'} <ArrowRight/></button></div></article><aside><h3>Available here</h3>{v.tags.map(x=><div key={x}>✓ {x}</div>)}<div>✓ Direct feedback</div><div>✓ Restaurant-owned loyalty</div></aside></section></main>}
