create extension if not exists pgcrypto;

create type public.app_role as enum ('owner','manager','cashier','waiter','kitchen','stock','admin');
create type public.order_status as enum ('new','confirmed','preparing','ready','served','billing','paid','cancelled');
create type public.order_source as enum ('qr','waiter','pos','takeaway','delivery');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,phone text,created_at timestamptz not null default now());
create table public.restaurants(id uuid primary key default gen_random_uuid(),name text not null,legal_name text,gstin text,fssai text,currency text not null default 'INR',timezone text not null default 'Asia/Kolkata',created_at timestamptz not null default now());
create table public.outlets(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,name text not null,address jsonb default '{}'::jsonb,phone text,opens_at time,closes_at time,active boolean not null default true,created_at timestamptz not null default now());
create table public.memberships(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,restaurant_id uuid not null references public.restaurants(id) on delete cascade,outlet_id uuid references public.outlets(id) on delete cascade,role public.app_role not null,active boolean not null default true,unique(user_id,restaurant_id,outlet_id,role));
create table public.restaurant_tables(id uuid primary key default gen_random_uuid(),outlet_id uuid not null references public.outlets(id) on delete cascade,label text not null,seats int not null default 4,public_code text not null unique default encode(gen_random_bytes(7),'hex'),x numeric default 0,y numeric default 0,state text not null default 'free',unique(outlet_id,label));
create table public.menu_categories(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,name text not null,sort_order int default 0,active boolean not null default true);
create table public.menu_items(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,category_id uuid references public.menu_categories(id) on delete set null,name text not null,description text,price numeric(12,2) not null,cost_target numeric(12,2),dietary text[],allergens text[],prep_minutes int default 15,image_url text,active boolean not null default true,created_at timestamptz not null default now());
create table public.ingredients(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,name text not null,purchase_unit text not null,base_unit text not null,unit_factor numeric not null default 1,avg_unit_cost numeric(12,4) not null default 0,on_hand numeric(14,3) not null default 0,reorder_level numeric(14,3) default 0,active boolean not null default true,unique(restaurant_id,name));
create table public.recipes(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,menu_item_id uuid references public.menu_items(id) on delete cascade,name text not null,yield_qty numeric not null default 1,yield_unit text not null default 'portion',active boolean not null default true);
create table public.recipe_components(id uuid primary key default gen_random_uuid(),recipe_id uuid not null references public.recipes(id) on delete cascade,ingredient_id uuid not null references public.ingredients(id) on delete restrict,qty numeric(14,4) not null,unit text not null);
create table public.orders(id uuid primary key default gen_random_uuid(),outlet_id uuid not null references public.outlets(id) on delete restrict,table_id uuid references public.restaurant_tables(id) on delete set null,customer_id uuid,source public.order_source not null,status public.order_status not null default 'new',subtotal numeric(12,2) not null default 0,discount numeric(12,2) not null default 0,tax numeric(12,2) not null default 0,total numeric(12,2) not null default 0,notes text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),paid_at timestamptz);
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,menu_item_id uuid not null references public.menu_items(id) on delete restrict,qty numeric(10,2) not null default 1,unit_price numeric(12,2) not null,modifiers jsonb default '[]'::jsonb,status public.order_status not null default 'new',station text,notes text);
create table public.kitchen_tickets(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,station text not null,status text not null default 'new',started_at timestamptz,ready_at timestamptz,served_at timestamptz);
create table public.suppliers(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,name text not null,phone text,email text,lead_time_hours int,reliability numeric(5,2),active boolean default true);
create table public.purchase_orders(id uuid primary key default gen_random_uuid(),outlet_id uuid not null references public.outlets(id) on delete restrict,supplier_id uuid references public.suppliers(id),status text not null default 'draft',expected_at timestamptz,total numeric(12,2) default 0,created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.purchase_order_items(id uuid primary key default gen_random_uuid(),purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade,ingredient_id uuid not null references public.ingredients(id),ordered_qty numeric(14,3) not null,received_qty numeric(14,3) default 0,unit_cost numeric(12,4) not null);
create table public.inventory_movements(id uuid primary key default gen_random_uuid(),outlet_id uuid not null references public.outlets(id) on delete cascade,ingredient_id uuid not null references public.ingredients(id) on delete restrict,movement_type text not null check(movement_type in('purchase','theoretical_usage','waste','transfer_in','transfer_out','count_adjustment','return')),qty numeric(14,3) not null,unit_cost numeric(12,4),reference_type text,reference_id uuid,note text,created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.waste_events(id uuid primary key default gen_random_uuid(),outlet_id uuid not null references public.outlets(id) on delete cascade,ingredient_id uuid references public.ingredients(id),menu_item_id uuid references public.menu_items(id),qty numeric(14,3) not null,unit text not null,reason text not null,cost numeric(12,2),photo_url text,approved_by uuid references auth.users(id),created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.customers(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,name text,phone text,email text,consent_marketing boolean not null default false,created_at timestamptz not null default now());
create table public.visits(id uuid primary key default gen_random_uuid(),customer_id uuid references public.customers(id) on delete cascade,outlet_id uuid not null references public.outlets(id),order_id uuid references public.orders(id),spend numeric(12,2) default 0,visited_at timestamptz not null default now());
create table public.feedback(id uuid primary key default gen_random_uuid(),outlet_id uuid not null references public.outlets(id),customer_id uuid references public.customers(id),order_id uuid references public.orders(id),rating int check(rating between 1 and 5),tags text[],comment text,created_at timestamptz not null default now());
create table public.expenses(id uuid primary key default gen_random_uuid(),outlet_id uuid not null references public.outlets(id),category text not null,amount numeric(12,2) not null,occurred_on date not null default current_date,note text,created_by uuid references auth.users(id));
create table public.audit_events(id bigint generated always as identity primary key,restaurant_id uuid references public.restaurants(id),outlet_id uuid references public.outlets(id),actor_id uuid references auth.users(id),action text not null,entity_type text,entity_id uuid,before_data jsonb,after_data jsonb,created_at timestamptz not null default now());

create or replace function public.is_restaurant_member(rid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from memberships m where m.restaurant_id=rid and m.user_id=auth.uid() and m.active); $$;
create or replace function public.can_manage_restaurant(rid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from memberships m where m.restaurant_id=rid and m.user_id=auth.uid() and m.active and m.role in('owner','manager','admin')); $$;

alter table public.profiles enable row level security;alter table public.restaurants enable row level security;alter table public.outlets enable row level security;alter table public.memberships enable row level security;alter table public.restaurant_tables enable row level security;alter table public.menu_categories enable row level security;alter table public.menu_items enable row level security;alter table public.ingredients enable row level security;alter table public.recipes enable row level security;alter table public.recipe_components enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.kitchen_tickets enable row level security;alter table public.suppliers enable row level security;alter table public.purchase_orders enable row level security;alter table public.purchase_order_items enable row level security;alter table public.inventory_movements enable row level security;alter table public.waste_events enable row level security;alter table public.customers enable row level security;alter table public.visits enable row level security;alter table public.feedback enable row level security;alter table public.expenses enable row level security;alter table public.audit_events enable row level security;

create policy "profile self" on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "restaurant members read" on public.restaurants for select using(public.is_restaurant_member(id));
create policy "restaurant managers update" on public.restaurants for update using(public.can_manage_restaurant(id));
create policy "outlet members" on public.outlets for select using(public.is_restaurant_member(restaurant_id));
create policy "membership self or managers" on public.memberships for select using(user_id=auth.uid() or public.can_manage_restaurant(restaurant_id));
create policy "members tables" on public.restaurant_tables for all using(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id))) with check(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id)));
create policy "public active categories" on public.menu_categories for select using(active=true);
create policy "members manage categories" on public.menu_categories for all using(public.can_manage_restaurant(restaurant_id)) with check(public.can_manage_restaurant(restaurant_id));
create policy "public active menu" on public.menu_items for select using(active=true);
create policy "members manage menu" on public.menu_items for all using(public.can_manage_restaurant(restaurant_id)) with check(public.can_manage_restaurant(restaurant_id));
create policy "members ingredients" on public.ingredients for all using(public.is_restaurant_member(restaurant_id)) with check(public.is_restaurant_member(restaurant_id));
create policy "members recipes" on public.recipes for all using(public.is_restaurant_member(restaurant_id)) with check(public.is_restaurant_member(restaurant_id));
create policy "members recipe components" on public.recipe_components for all using(exists(select 1 from recipes r where r.id=recipe_id and public.is_restaurant_member(r.restaurant_id))) with check(exists(select 1 from recipes r where r.id=recipe_id and public.is_restaurant_member(r.restaurant_id)));
create policy "members orders" on public.orders for all using(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id))) with check(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id)));
create policy "members order items" on public.order_items for all using(exists(select 1 from orders o join outlets x on x.id=o.outlet_id where o.id=order_id and public.is_restaurant_member(x.restaurant_id))) with check(exists(select 1 from orders o join outlets x on x.id=o.outlet_id where o.id=order_id and public.is_restaurant_member(x.restaurant_id)));
create policy "members kitchen" on public.kitchen_tickets for all using(exists(select 1 from orders o join outlets x on x.id=o.outlet_id where o.id=order_id and public.is_restaurant_member(x.restaurant_id))) with check(exists(select 1 from orders o join outlets x on x.id=o.outlet_id where o.id=order_id and public.is_restaurant_member(x.restaurant_id)));
create policy "members suppliers" on public.suppliers for all using(public.is_restaurant_member(restaurant_id)) with check(public.is_restaurant_member(restaurant_id));
create policy "members purchase orders" on public.purchase_orders for all using(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id))) with check(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id)));
create policy "members purchase items" on public.purchase_order_items for all using(exists(select 1 from purchase_orders p join outlets o on o.id=p.outlet_id where p.id=purchase_order_id and public.is_restaurant_member(o.restaurant_id))) with check(exists(select 1 from purchase_orders p join outlets o on o.id=p.outlet_id where p.id=purchase_order_id and public.is_restaurant_member(o.restaurant_id)));
create policy "members inventory" on public.inventory_movements for all using(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id))) with check(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id)));
create policy "members waste" on public.waste_events for all using(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id))) with check(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id)));
create policy "members customers" on public.customers for all using(public.is_restaurant_member(restaurant_id)) with check(public.is_restaurant_member(restaurant_id));
create policy "members visits" on public.visits for all using(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id))) with check(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id)));
create policy "members feedback" on public.feedback for select using(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id)));
create policy "public feedback create" on public.feedback for insert to anon,authenticated with check(rating between 1 and 5);
create policy "members expenses" on public.expenses for all using(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id))) with check(exists(select 1 from outlets o where o.id=outlet_id and public.is_restaurant_member(o.restaurant_id)));
create policy "managers audit" on public.audit_events for select using(public.can_manage_restaurant(restaurant_id));

create index on public.memberships(user_id,restaurant_id);create index on public.orders(outlet_id,created_at desc);create index on public.order_items(order_id);create index on public.inventory_movements(outlet_id,ingredient_id,created_at desc);create index on public.waste_events(outlet_id,created_at desc);create index on public.visits(customer_id,visited_at desc);
